# Graph Construction Configuration
# Configuration file for building heterogeneous graphs for music recommendation

# Data paths
data:
  input_dir: "data/processed/gnn_ready"  # Directory with preprocessed data
  output_dir: "data/processed/graphs"     # Directory to save graphs

# Graph construction settings
graph:
  # Node type mappings (entity_name -> graph_node_name)
  node_type_mapping:
    playlists: "playlist"
    tracks: "track"
    artists: "artist"
    albums: "album"
    users: "user"

  # Edge type definitions (edge_name -> (src_type, relation, dst_type))
  edge_type_mapping:
    playlist_track: ["playlist", "contains", "track"]
    track_artist: ["track", "performed_by", "artist"]
    track_album: ["track", "belongs_to", "album"]
    user_playlist: ["user", "created", "playlist"]
    playlist_user: ["playlist", "created_by", "user"]

  # Data splits configuration
  splits:
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15

  # Feature normalization
  features:
    normalize: true
    normalize_method: "standard"  # standard, minmax, robust

# Validation settings
validation:
  check_nan_values: true
  check_edge_indices: true
  verify_node_features: true

# Output settings
output:
  save_metadata: true
  save_visualizations: false  # Set to true to save graph statistics plots
  compression: false  # Set to true to compress saved graphs

# Memory optimization
memory:
  use_sparse_tensors: false
  chunk_size: 10000  # For processing large datasets in chunks

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  save_logs: true
  log_file: "logs/graph_construction.log"

# Random seed for reproducibility
random_seed: 42

# Advanced settings
advanced:
  # Whether to create bidirectional edges automatically
  add_reverse_edges: false

  # Whether to add self-loops
  add_self_loops: false

  # Edge sampling (for very large graphs)
  edge_sampling:
    enabled: false
    max_edges_per_type: 1000000

  # Node sampling (for very large graphs)
  node_sampling:
    enabled: false
    max_nodes_per_type: 100000