# Data Preprocessing Configuration for GNN Music Recommender

# Input/Output paths
data:
  input_file: "data/processed/spotify_hybrid_sampled_50000.json"
  output_dir: "data/processed/gnn_ready"

# Data splitting configuration
splits:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  random_seed: 42

# Feature extraction configuration
features:
  # Playlist features
  playlist:
    include_basic: true      # num_tracks, num_followers, collaborative
    include_temporal: true   # modified_at normalized
    include_text: true       # name length, has_name

  # Track features
  track:
    include_popularity: true  # playlist_count (log transformed)
    include_position: true    # avg_position, position_std
    include_duration: true    # duration in minutes

  # User features
  user:
    include_activity: true    # playlist_count (log transformed)
    include_diversity: true   # unique_track_count (log transformed)
    include_behavior: true    # avg_playlist_length, collaborative_ratio

# Graph construction configuration
graph:
  edge_types:
    - "playlist_track"  # Main edges for recommendation
    - "track_artist"    # Track-artist relationships
    - "track_album"     # Track-album relationships
    - "user_playlist"   # User-playlist relationships
    - "playlist_user"   # Reverse user-playlist

  remove_duplicates: true

# Negative sampling configuration
negative_sampling:
  strategy: "random"
  ratio: 1.0  # 1:1 positive to negative ratio
  max_attempts_multiplier: 10

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

# Reproducibility
reproducibility:
  set_random_seed: true
  numpy_seed: 42
  python_seed: 42